# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: RecipeRevive jest Test

on:
  push:
    branches: [ "dev", "azuhayer:dev"]
  pull_request:
    branches: [ "dev", "azuhayer:dev"]

jobs:
  build:

    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [14.x, 16.x, 18.x]
    #     # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout the PR
      uses: actions/checkout@v3
    
    - name: Install node 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Build the next.js project
      run: npm run build 

    - name: Jest Test
      run: npm test test:coverage



    - name: Upload unit and integration test code coverage
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: unit and integration test coverage
        path: coverage/
        retention-days: 30
              