name: RecipeRevive jest Test

on:
  pull_request:
    branches: [ "dev", "azuhayer:dev" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the PR
      uses: actions/checkout@v3
    
    - name: Install node 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci
    
    
    - name: Build the next.js project
      run: npm run build 
    
    - name: Run unit/integration tests and generate converage
      run: npm run test:coverage
    

    - name: Upload unit and integration test code coverage
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: unit and integration test coverage
        path: coverage/
        retention-days: 30