name: CI Setup

on:
  pull_request:
    branches: 
    - workflow-setup
    - dev
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the PR
      uses: actions/checkout@v3
    
    - name: Install node 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci


