# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: jest Test 2

on:
  workflow_dispatch:
  pull_request:
    branches: [ "dev", "azuhayer:dev" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the PR
      uses: actions/checkout@v3
    
    - name: Install node 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci
    
    
    - name: Build the next.js project
      run: npm run build 
    
    - name: Run unit/integration tests and generate converage
      run: npm run test:coverage
    

    - name: Upload unit and integration test code coverage
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: unit and integration test coverage
        path: coverage/
        retention-days: 30
